In [7]:
import dgl
import dgl.ops as F
import dgl.function as fn
import torch as th
g = dgl.graph((th.tensor([0, 1, 2]), th.tensor([1, 2, 0])))
g.ndata['h'] = th.tensor([[0.], [1.], [2.]])
g.edata['h'] = th.tensor([[3.], [4.], [5.]])
g

Graph(num_nodes=3, num_edges=3,
      ndata_schemes={'h': Scheme(shape=(1,), dtype=torch.float32)}
      edata_schemes={'h': Scheme(shape=(1,), dtype=torch.float32)})

In [5]:
rg=dgl.reverse(g,copy_edata=True)
rg

Graph(num_nodes=3, num_edges=3,
      ndata_schemes={'h': Scheme(shape=(1,), dtype=torch.float32)}
      edata_schemes={'h': Scheme(shape=(1,), dtype=torch.float32)})

In [12]:
hg1 = dgl.heterograph({
      ('user', 'plays', 'game') : (torch.tensor([0, 1]), torch.tensor([0, 0]))})
hg2 = dgl.heterograph({
      ('user', 'plays', 'game') : (torch.tensor([0, 0]), torch.tensor([1, 0]))})
bg = dgl.batch([hg1, hg2])
bg.batch_num_nodes('user')

tensor([2, 1])

In [3]:
rg.ndata

{'h': tensor([[0.],
        [1.],
        [2.]])}

In [1]:
import torch
x=torch.randn(10,5)

/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([[ 1.2037, -0.4810,  0.3482, -0.1376,  1.0303],
        [-1.9557,  0.4084,  0.6478, -1.1810,  1.0980],
        [-0.5299,  0.0475, -0.0899, -0.2299, -1.4117],
        [-1.5853,  0.2675,  1.2206, -0.0452, -0.0826],
        [-0.2812, -0.4648,  0.2507,  0.2640, -0.2663],
        [-0.2311,  1.2283,  0.6217,  1.0362,  0.5826],
        [-0.3911,  0.0486, -0.7912,  1.5651,  2.4715],
        [ 1.3550, -0.9931, -0.7721,  1.5138,  0.5665],
        [ 0.0246, -0.9837, -0.2204,  0.9296, -2.3206],
        [-0.1285,  2.4950,  0.8063,  0.4360, -1.2972]])

In [3]:
torch.sigmoid(x)

tensor([[0.7692, 0.3820, 0.5862, 0.4657, 0.7370],
        [0.1239, 0.6007, 0.6565, 0.2349, 0.7499],
        [0.3706, 0.5119, 0.4775, 0.4428, 0.1960],
        [0.1700, 0.5665, 0.7722, 0.4887, 0.4794],
        [0.4302, 0.3858, 0.5624, 0.5656, 0.4338],
        [0.4425, 0.7735, 0.6506, 0.7381, 0.6417],
        [0.4034, 0.5121, 0.3119, 0.8271, 0.9221],
        [0.7949, 0.2703, 0.3160, 0.8196, 0.6379],
        [0.5062, 0.2722, 0.4451, 0.7170, 0.0894],
        [0.4679, 0.9238, 0.6913, 0.6073, 0.2146]])

In [1]:
import sys
sys.path

['/home/ec2-user/SageMaker/sequence-based-recommendation/SRGNN',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python38.zip',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python3.8',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python3.8/lib-dynload',
 '',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python3.8/site-packages']

In [3]:
import os
root_dir='/home/ec2-user/SageMaker/sequence-based-recommendation'
model_name="SRGNN"
model_path=os.path.join(root_dir,model_name)
model_path

'/home/ec2-user/SageMaker/sequence-based-recommendation/SRGNN'

In [4]:
sys.path.append(model_path)
sys.path

['/home/ec2-user/SageMaker/sequence-based-recommendation/SRGNN',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python38.zip',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python3.8',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python3.8/lib-dynload',
 '',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python3.8/site-packages',
 '/home/ec2-user/SageMaker/sequence-based-recommendation/SRGNN']

In [5]:
set(sys.path)

{'',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python3.8',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python3.8/lib-dynload',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python3.8/site-packages',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python38.zip',
 '/home/ec2-user/SageMaker/sequence-based-recommendation/SRGNN'}

In [6]:
sys.path=list(set(sys.path))
sys.path

['',
 '/home/ec2-user/SageMaker/sequence-based-recommendation/SRGNN',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python3.8',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python38.zip',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python3.8/lib-dynload',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python3.8/site-packages']

In [7]:
sys.path=[x for x in sys.path if x !=model_path]
sys.path

['',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python3.8',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python38.zip',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python3.8/lib-dynload',
 '/home/ec2-user/SageMaker/.cs/conda/envs/SRGNN/lib/python3.8/site-packages']